# Generated by Django 3.1.1 on 2020-09-26 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RouterDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sapid', models.CharField(max_length=256)),
                ('hostname', models.CharField(max_length=256)),
                ('loopback', models.CharField(max_length=256)),
                ('mac_addr', models.CharField(max_length=256)),
                ('ip_addr', models.CharField(max_length=256)),
                ('active', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'router_details',
            },
        ),
    ]
