# Generated by Django 3.1.1 on 2020-09-26 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('router_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routerdetails',
            name='ip_addr',
        ),
        migrations.AlterField(
            model_name='routerdetails',
            name='loopback',
            field=models.GenericIPAddressField(),
        ),
    ]
